name: Deploy to Kubernetes Cluster

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: kade93/kade-im-webapp
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          # tag: test-action

          # cache: true
          # cache-repository: ${{ secrets.DOCKER_REPOSITORY }}/kade-im-webapp/cache
          # build-args: |
            # --destination=${{ secrets.DOCKER_REPOSITORY}}/kade-im-webapp:${{ github.ref_name }}-v${{ github.run_number }}
  deploy:
    needs: build
    runs-on: self-hosted
    steps:

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/kade-im-deploy kade-im=${{ secrets.DOCKER_REPOSITORY }}/kade-im-webapp:${{ github.ref_name }}-v${{ github.run_number }} --namespace default