name: Deploy to Kubernetes Cluster

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and push Docker image with Kaniko
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
      run: |
        mkdir -p /kaniko/.docker
        echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"username\":\"${DOCKER_USERNAME}\",\"password\":\"${DOCKER_PASSWORD}\"}}}" > /kaniko/.docker/config.json
        /kaniko/executor --context $GITHUB_WORKSPACE --dockerfile $GITHUB_WORKSPACE/Dockerfile --destination ${DOCKER_REPOSITORY}/:${{ github.sha }} --cache

    - name: Update Kubernetes Deployment
      run: |
        kubectl set image deployment/kade-im-deploy kade-im=${{ secrets.DOCKER_USERNAME }}/kade-im-webapp:${{ github.sha }} --namespace default
