name: Deploy to Kubernetes Cluster

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and push Docker image with Buildah
      run: |
        buildah bud -t ${DOCKER_REPOSITORY}/kade-im-webapp:${{ github.sha }} -f $GITHUB_WORKSPACE/Dockerfile $GITHUB_WORKSPACE
        buildah push ${DOCKER_REPOSITORY}/kade-im-webapp:${{ github.sha }}
      env:
        DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Update Kubernetes Deployment
      run: |
        kubectl set image deployment/kade-im-deploy kade-im=${DOCKER_REPOSITORY}/kade-im-webapp:${{ github.sha }} --namespace default
