name: Deploy to Kubernetes Cluster

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - uses: int128/kaniko-action@v1
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache: true
          cache-repository: ${{ secrets.DOCKER_REPOSITORY }}/kade-im-webapp/cache
          build-args: |
            --destination=${{ secrets.DOCKER_REPOSITORY}}/kade-im-webapp:${{ github.ref_name }}-v${{ github.run_number }}
  deploy:
    needs: build
    runs-on: self-hosted
    steps:

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/kade-im-deploy kade-im=${{ secrets.DOCKER_REPOSITORY }}/kade-im-webapp:${{ github.ref_name }}-v${{ github.run_number }} --namespace default